# Generated by Django 4.1 on 2022-08-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('picture', models.CharField(max_length=400, unique=True)),
                ('description', models.CharField(max_length=2000)),
                ('meaning', models.CharField(max_length=2000)),
                ('kind', models.CharField(choices=[('MA', 'Arcano Mayor'), ('MI', 'Arcano Menor')], max_length=2)),
                ('suit', models.CharField(choices=[('ES', 'Espadas'), ('CO', 'Copas'), ('OR', 'Oros'), ('BA', 'Bastos')], max_length=2)),
            ],
        ),
    ]
